// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: delete_follow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteFollow = `-- name: DeleteFollow :exec
DELETE FROM feed_follows
WHERE feed_follows.user_id = $1
  AND feed_id IN (
      SELECT id FROM feeds WHERE url = $2
)
`

type DeleteFollowParams struct {
	UserID uuid.UUID
	Url    string
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) error {
	_, err := q.db.ExecContext(ctx, deleteFollow, arg.UserID, arg.Url)
	return err
}
